[package]
name = "rlasp-jit"
version.workspace = true
edition.workspace = true

[dependencies]
rlasp-runtime = { path = "../rlasp-runtime" }
rlasp-ffi = { path = "../rlasp-ffi" }
rlasp-reader = { path = "../rlasp-reader" }
inkwell = { workspace = true }
llvm-sys = { workspace = true }
malachite = { workspace = true }
malachite-base = { workspace = true }
malachite-q = { workspace = true }
num-complex = { workspace = true }

[lib]
name = "rlasp_jit"
path = "src/lib.rs"
