[package]
name = "rlasp-compiler"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
rlasp-runtime = { path = "../rlasp-runtime" }
rlasp-reader = { path = "../rlasp-reader" }
thiserror = { workspace = true }
dashmap = { workspace = true }

[dev-dependencies]
