[package]
name = "irlasp"
version.workspace = true
edition.workspace = true

[features]
default = ["boehm-gc"]
boehm-gc = ["rlasp-runtime/boehm-gc"]

[dependencies]
rlasp = { path = "../rlasp" }
rlasp-compiler = { path = "../rlasp-compiler" }
rlasp-jit = { path = "../rlasp-jit" }
rlasp-runtime = { path = "../rlasp-runtime" }
rlasp-reader = { path = "../rlasp-reader" }
rlasp-mlir = { path = "../rlasp-mlir" }
rustyline = "14.0.0"
# Link to librlasp dynamically via C ABI
libc = { workspace = true }
inkwell = { workspace = true }
llvm-sys = { workspace = true }
clap = { version = "4.5", features = ["derive"] }
num-complex = { workspace = true }

[build-dependencies]
# No dependencies needed for build script

[lib]
name = "irlasp"
path = "src/lib.rs"
crate-type = ["rlib", "cdylib", "staticlib"]

[[bin]]
name = "irlasp"
path = "src/main.rs"
