[package]
name = "rlasp-runtime"
version.workspace = true
edition.workspace = true

[dependencies]
parking_lot = { workspace = true }
crossbeam = { workspace = true }
lazy_static = { workspace = true }
num-bigint = { workspace = true }
num-rational = { workspace = true }
num-complex = { workspace = true }
num-traits = { workspace = true }
thiserror = { workspace = true }
# bdwgc-alloc = { workspace = true }  # Uncomment for Boehm GC

[lib]
name = "rlasp_runtime"
path = "src/lib.rs"
