[package]
name = "rlasp-runtime"
version.workspace = true
edition.workspace = true
build = "build.rs"

[features]
default = []
boehm-gc = []

[dependencies]
parking_lot = { workspace = true }
crossbeam = { workspace = true }
lazy_static = { workspace = true }
malachite = { workspace = true }
malachite-base = { workspace = true }
malachite-q = { workspace = true }
num-complex = { workspace = true }
thiserror = { workspace = true }
libc = { workspace = true }

[build-dependencies]
pkg-config = "0.3"

[lib]
name = "rlasp_runtime"
path = "src/lib.rs"
crate-type = ["rlib", "cdylib", "staticlib"]
