[package]
name = "rlasp-mlir"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
rlasp = { path = "../rlasp" }
rlasp-compiler = { path = "../rlasp-compiler" }
rlasp-jit = { path = "../rlasp-jit" }
inkwell.workspace = true
anyhow.workspace = true
thiserror.workspace = true

[dev-dependencies]
rlasp-runtime = { path = "../rlasp-runtime" }

[build-dependencies]
